theme: jekyll-theme-minimal
title: Ahmad Babaeian Jelodar
email: ajelodar@usf.edu
logo: images/logo1.png
description: Computer science researcher working on the computer vision side of robotics applications.
